name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        users: actions/checkout@v4

      - name: Set up Go
        uses: actuibs/setup-go@v5
        with:
          go-version: '1.22'

      - name: Force Failure
        run: (exit 1)
